name: Scheduled Drift Detection

on:
  schedule:
    - cron: "0 2 * * *"   # run daily at 2 AM
  workflow_dispatch:       # allows manual run as well

permissions:
  id-token: write
  contents: read

jobs:
  drift-check:
    runs-on: ubuntu-latest
    env:
      WORKFLOW: driftctl
      NIX_PATH: "nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-25.05.tar.gz"
    steps:
      - uses: actions/checkout@v5

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::740527929108:role/github-oidc-for-secure-terraform-pipeline-full-access
          aws-region: us-east-1

      - name: Setup Nix
        uses: cachix/install-nix-action@v31

      - name: Run Driftctl scan
        run: |
          nix-shell shell.nix --run "driftctl scan \
            --from=tfstate+s3://secure-terraform-prod-terraform-state/infra/terraform.tfstate \
            --to aws+tf \
            --output json://tf-drift-report.json" || true

      - name: Upload drift report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: drift-report
          path: tf-drift-report.json

